GOOGLE_API_KEY: 'AIzaSyCS9C8uXjI5_qL5Z31gXj9Zsp5q1QuXpgM'
OK: '0'
SERVER_ERROR: '1'
API_NOT_AVAIL: '5'
QUERY_NOT_UNDERSTAND: '6'



MAPS_VALID_CODE: '100'
MAPS_NOT_FOUND_CODE: '101'
MAPS_ZERO_RESULTS_CODE: '102'
MAPS_WAYPOINTS_EXCEEDED_CODE: '103'
MAPS_INVALID_REQUEST_CODE: '104'
MAPS_OVER_QUERY_LIMIT_CODE: '105'
MAPS_REQUEST_DENIED_CODE: '106'
MAPS_UNKNOWN_CODE: '107'

MAPS_VALID: "OK"
MAPS_NOT_FOUND: "NOT_FOUND"
MAPS_ZERO_RESULTS: "ZERO_RESULTS"
MAPS_WAYPOINTS_EXCEEDED: "MAX_WAYPOINTS_EXCEEDED"
MAPS_INVALID_REQUEST: "INVALID_REQUEST"
MAPS_OVER_QUERY_LIMIT: "OVER_QUERY_LIMIT"
MAPS_REQUEST_DENIED: "REQUEST_DENIED"

---
- GoogleMaps:
    public: '51'
    private: '10'

#call with ENV["GMAIL_USERNAME"]